config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  # get 'books/index'
  # get 'books/create'
  # get 'books/edit'
  # get 'books/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ブックモデルのルーティング
  # ブックコントローラ
  resources :books, only: [:edit, :create, :index, :show, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # # ホームのコントローラ
  root "homes#top"
  get "home/about" => "homes#index"


  # ユーザーモデルのルーティング
  # ユーザーコントローラ
  resources :users, only: [:show, :edit, :update, :index] do
    # フォローリスト
    get "followlist" => "relationships#followlist" 
    # フォロワーリスト
    get "followerlist" => "relationships#followerlist" 
  
  end


  # ログイン認証が成功した後、投稿画像の一覧画面が表示される
  # root 'books#index'

  # フォローのルーティング
  post 'create/:id' => 'relationships#create', as: 'create' # フォローする
  post 'destroy/:id' => 'relationships#destroy', as: 'destroy' # フォロー外す
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # ユーザーがファボしたかどうかを確認するメソッド
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { in: 1..200 }
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  # 1つツイートに1つのユーザーしかいいねができないよう制限
  validates :book_id, uniqueness: { scope: :user_id }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  # フォローする・フォロー外す・フォローしているか確認を行うメソッド
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
  
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


  # ログインしたあとに飛ぶページの設定
  def after_sign_in_path_for(resource)
    user_path(current_user.id) 
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @new = Book.new
    @book_comment = BookComment.new
    @book_comment_new = current_user.book_comments.new(book_comment_params)
    @book_comment_new.book_id = @book.id
    @user = current_user

   @book_comment_new.save

  end


  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    # redirect_to request.referrer
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
    redirect_to book_path(@book.id), notice: "You have creatad book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user.id != current_user.id
      redirect_to books_path
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_comment_new = BookComment.new
    @new = Book.new
    @user = current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
     render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: root_path)
    # redirect_to request.referrer
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)
    # redirect_to request.referrer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  

  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  
  def followlist
    @user = User.find(params[:user_id])
  end
  
  def followerlist
     @user = User.find(params[:user_id])
  end
  
  def create
  current_user.follow(params[:id])
  redirect_to request.referrer
  end

  def destroy
    current_user.unfollow(params[:id])
    redirect_to request.referrer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.all
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
      
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path, notice: "You have updated user successfully."
    else
     render :edit
    end

  end


  private
  def user_params
     params.require(:user).permit(:profile_image, :name, :introduction)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comments.html.erb
<!--コメント件数の部分-->
<div class="comment-list">
    <div class="float-wrapper">
        <h2 class="comment-count"><%= book.book_comments.count %>件コメント</h2>
    </div>
</div>

<table class="table">
    <tbody>
        <!--コメント一覧部分-->
        <% book.book_comments.each do |book_comment| %>
     <tr>
           <td><%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50" %></td>
           <td><%= book_comment.comment %></td>
           <td>
               <% if book_comment.user == current_user %>
                   <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
               <% end %>
           </td>
     </tr>
        <% end %>
    </tbody>
</table>


<!--コメントフォーム-->
<%= form_with(model:[book,book_comment] ,remote: true) do |f| %>
            <div id="error_explanation">
            </div>
    <%= f.text_area :comment, class: "form-control",placeholder: "ここへコメントを記入！！" %>
    <%= f.submit "送信する！" %>
<% end %>

app/views/book_comments/_error.html.erb
<% if comment.errors.any? %>

  <div class="error_message alert alert-warning">
    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/book_comments/create.js.erb
$('#book_comments_buttons_<%= @book.id %>').html("<%= j(render partial: 'book_comments/book_comments', locals: {book: @book,book_comment:@book_comment}) %>");
$("#error_explanation").html("<%= j(render 'error', { comment: @book_comment_new }) %>");

app/views/book_comments/destroy.js.erb
$('#book_comments_buttons_<%= @book.id %>').html("<%= j(render partial: 'book_comments/book_comments', locals: {book: @book,book_comment: @book_comment}) %>");

app/views/books/edit.html.erb
<!--編集画面-->

<div class="notice">
  <%= notice %>
</div>

<!--エラー文章部分-->
<div class="error">
<% if @book.errors.any? %>
    <h2><%= @book.errors.count %>error</h2>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>
</div>
    
<h1>Editing Book</h1>
<%= form_with model:@book, url: book_path(@book.id), local:true do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book', class:"btn btn-info active" %>
    <%= link_to "Show", book_path(@book.id), class: "btn btn-info active" %>
    <%= link_to "Back", books_path,  class: "btn btn-info active" %>
<% end %> 

app/views/books/index.html.erb
<div class="notice">
  <%= notice %>
</div>

 <!--エラー文章部分-->
<% if @book.errors.any? %>
<h2><%= @book.errors.count %>error</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <!--マイページ表示部分-->
      <h1>User info</h1>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
          <th></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
          <th></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to @user.follower.count, user_followlist_path(@user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to @user.followed.count, user_followerlist_path(@user) %></th>
        </tr>
      </table>
      <button type="button" class="btn btn-default" aria-label="Left Align"><%= link_to '', edit_user_path(current_user.id), class: "glyphicon glyphicon-wrench" %></button>
　　　<!--フォローボタン-->
      <% unless @user == current_user %>
        <% if current_user.following?(@user) %>
            <%= link_to 'フォロー外す', destroy_path(@user.id), method: :POST , class: "btn btn-info active"%>
        <% else %>
            <%= link_to 'フォローする', create_path(@user.id), method: :POST , class: "btn btn-info active" %>
        <% end %>
      <% end %>

      <!--投稿部分-->
      <h1>New book</h1>
      <!-- form_with部分 -->
      <%= form_with model:@book, url: books_path, local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book', class: "btn btn-info active" %>
      <% end %>
    </div>


    <div class="col-xs-9">
      <!--一覧部分-->
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"60x60" %>
              <% end %>
            </td>
            <td><%=  link_to book.title, book_path(book.id) %></td>
            <td><%=  book.body %></td>
            
            <!--いいね部分テンプレート-->
            <td>
              <div id="favorites_buttons_<%= book.id %>">
                <%= render partial: 'favorites/favorites', locals: { book: book} %>
              </div>
            </td>
            <td><%= book.book_comments.count %>件コメント</td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<!--詳細ページ-->

<div class="notice">
  <%= notice %>
</div>

<!--エラー文章部分-->
<div class="error">
    <% if @new.errors.any? %>
        <h2><%= @new.errors.count %>件のエラーが発生しました。</h2>
        <ul>
            <% @new.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-3">
            <!--マイページ表示部分-->
            <h1>User info</h1>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"60x60" %>
            <table class="table">
                <tr>
                    <th>name</th>
                    <th><%= @book.user.name %></th>
                    <th></th>
                </tr>
                <tr>
                    <th>introduction</th>
                    <th><%= @book.user.introduction %></th>
                    <th></th>
                </tr>
            <tr>
              <th>follows</th>
              <th><%= link_to @book.user.follower.count, user_followlist_path(@book.user) %></th>
            </tr>
            <tr>
              <th>followers</th>
              <th><%= link_to @book.user.followed.count, user_followerlist_path(@book.user) %></th>
            </tr>
            </table>
            <button type="button" class="btn btn-default" aria-label="Left Align"><%= link_to '', edit_user_path(@book.user.id), class: "glyphicon glyphicon-wrench" %></button>
            <!--フォローボタン-->
              <% unless @book.user == current_user %>
                <% if current_user.following?(@book.user) %>
                    <%= link_to 'フォロー外す', destroy_path(@book.user), method: :POST , class: "btn btn-info active"%>
                <% else %>
                    <%= link_to 'フォローする', create_path(@book.user), method: :POST , class: "btn btn-info active" %>
                <% end %>
              <% end %>

            <!--投稿部分-->
            <h1>New book</h1>
            <!-- form_with部分 -->
            <%= form_for (@new) do |f| %>
                <h4>Title</h4>
                <%= f.text_field :title %>
                <h4>Opinion</h4>
                <%= f.text_area :body %>
                <%= f.submit 'Create Book',  class: "btn btn-info active"  %>
            <% end %>
        </div>


        <div class="col-xs-9">
            <!--本の詳細部分-->
            <h1>Book detail</h1>
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <%= link_to user_path(@book.user.id) do %>
                                <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"60x60" %>
                                </br>
                                <%= @book.user.name %>
                            <% end %>
                        </td>
                        <td>
                            <!--タイトル-->
                            <p><%= link_to @book.title, book_path(@book.id) %></p>
                        </td>
                        <td>
                            <!--オピニオン-->
                            <p><%= @book.body %></p>
                        </td>
                        <td>
                            <div id="favorites_buttons_<%= @book.id %>">
                                <%= render partial: 'favorites/favorites', locals: { book: @book} %>
                         　 </div>
                        </td>
                        <!--コメント部分-->
                        <td>
                            <i class="fa fa-comment">コメント数：</i>
                            <a href="#comments"><%= @book.book_comments.count %></a>
                        </td>

                    <!--もしログインしてるユーザーと投稿した人が一致していたら表示できる-->
                    <% if @book.user == current_user %>

                        <td>
                         <%= link_to "Edit", edit_book_path(@book.id),  class: "btn btn-info active" %>
                        </td>
                 　  　　<td>
                　        <%= link_to "Destroy", book_path(@book.id), class: "btn btn-default", method: :delete, "data-confirm" => "本当に消しますか？?" %>
                　   　  </td>

                    <% end %>
                    </tr>
                </tbody>
            </table>

            <!--コメントの部分テンプレート-->
            <div id="book_comments_buttons_<%= @book.id %>">
                <%= render partial: 'book_comments/book_comments', locals: { book: @book, book_comment: @book_comment_new} %>
            </div>






        </div>
    </div>
</div>

app/views/favorites/_favorites.html.erb
 <!--いいね部分-->
<% if book.favorited_by?(current_user) %>

  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
  <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
  <% end %>
  <span><%= book.favorites.count %>いいね</span>

<% else %>

  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
   <i class="glyphicon glyphicon-heart-empty" style="color: red;"></i>
  <% end %>
  <span><%= book.favorites.count %>いいね</span>

<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorites', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorites', locals: {book: @book}) %>");

app/views/homes/index.html.erb
<!--aboutページ-->

<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>

app/views/homes/top.html.erb
<!--ログインする前のページ-->
<!--トップページ-->
<div class="notice">
  <%= notice %>
</div>

<div class="container">
  <div class="row">
    <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
    <h2>
      In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,<br>
    you can share and exchange your opinions , inpressions , and emotions<br>
    about various books!
    </h2>
    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to "log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
      </div>
      <div class="row">
        <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followerlist.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      
      <h1>Follower List</h1>
      
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
      
        <tbody>
          <tr>
          <% @user.follower_user.each do |follower| %>
            <td><%= attachment_image_tag follower, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"60x50" %></td>
            <td><%= follower.name %></td>
            <td><%= "フォロー数: #{follower.follower.count}" %></td>
            <td><%= "フォロワー数: #{follower.followed.count}" %></td>
            <td><td><%= link_to "Show", user_path(follower.id), class: "btn btn-info active" %></td></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/relationships/followlist.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Follow List</h1>

      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <tr>
          <% @user.following_user.each do |follower| %>
            <td><%= attachment_image_tag follower, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"60x50" %></td>
            <td><%= follower.name %></td>
            <td><%= "フォロー数: #{follower.follower.count}" %></td>
            <td><%= "フォロワー数: #{follower.followed.count}" %></td>
            <td><td><%= link_to "Show", user_path(follower.id), class: "btn btn-info active" %></td></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<!--エラー文章部分-->
<% if @user.errors.any? %>
  <h2><%= @user.errors.count %>error</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<!--ユーザー情報編集ページ-->
<h1>User info</h1>
<%= form_with model:@user, local:true do |f| %>
  <h2>Name</h2>
  <%= f.text_field :name %>
  <h2>Image</h2>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
  <h2>Introduction</h2>
  <%= f.text_area :introduction %>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<!--登録したアカウント一覧ページ-->

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <!--マイページ表示部分-->
      <h1>User info</h1>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"60x60" %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
          <th></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
          <th></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to @user.follower.count, user_followlist_path(@user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to @user.followed.count, user_followerlist_path(@user) %></th>
        </tr>
      </table>

      <button type="button" class="btn btn-default btn-lg active" aria-label="Left Align"><%= link_to '', edit_user_path(current_user.id), class: "glyphicon glyphicon-wrench" %></button>
      <!--フォローボタン-->
      <% unless @user == current_user %>
        <% if current_user.following?(@user) %>
            <%= link_to 'フォロー外す', destroy_path(@user.id), method: :POST , class: "btn btn-info active"%>
        <% else %>
            <%= link_to 'フォローする', create_path(@user.id), method: :POST , class: "btn btn-info active" %>
        <% end %>
      <% end %>

      <!--投稿部分-->
      <h1>New book</h1>
      <!-- form_with部分 -->
      <%= form_with model:@book, url: books_path, local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book', class: "btn btn-info active"%>
      <% end %>
    </div>

    <div class="col-xs-9">
     <h1>Users</h1>
      <table class="table">
        <!--登録したアカウントの一覧部分-->
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"60x50" %></td>
                <td><%= user.name %></td>
                <td><%= "フォロー数: #{user.follower.count}" %></td>
                <td><%= "フォロワー数: #{user.followed.count}" %></td>
                <td>
                  <!--フォローボタン-->
                  <% if current_user.id != user.id %>
                    <% if current_user.following?(user) %>
                        <%= link_to 'フォロー外す', destroy_path(user.id), method: :POST , class: "btn btn-info active"%>
                    <% else %>
                        <%= link_to 'フォローする', create_path(user.id), method: :POST , class: "btn btn-info active" %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= link_to "Show", user_path(user.id), class: "btn btn-info active" %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--ホームページ（HOME）-->


<!--成功文-->
<div class="notice">
<%= notice %>
</div>

<!--エラー文章部分-->
<% if @book.errors.any? %>
  <h2><%= @book.errors.count %>error</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <!--マイページ表示部分-->
      <h1>User info</h1>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:"60x60"%>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to @user.follower.count, user_followlist_path(@user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to @user.followed.count, user_followerlist_path(@user) %></th>
        </tr>
      </table>
      <button type="button" class="btn btn-default" aria-label="Left Align"><%= link_to '', edit_user_path(@user.id), class: "glyphicon glyphicon-wrench" %></button>
      <!--フォローボタン-->
      <% unless @user == current_user %>
        <% if current_user.following?(@user) %>
            <%= link_to 'フォロー外す', destroy_path(@user.id), method: :POST , class: "btn btn-info active"%>
        <% else %>
            <%= link_to 'フォローする', create_path(@user.id), method: :POST , class: "btn btn-info active" %>
        <% end %>
      <% end %>


      <!--投稿部分-->
      <h1>New book</h1>
      <%= form_with model:@book, url: books_path, local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book', class: "btn btn-info active" %>
      <% end %>
    </div>


    <div class="col-xs-9">
      <!--一覧部分-->
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50"%>
              <% end %>
            </td>
            <td><%=  link_to book.title, book_path(book.id) %></td>
            <td><%=  book.body %></td>
            <td><%= book.book_comments.count %>件コメント</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>