config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  # get 'books/index'
  # get 'books/create'
  # get 'books/edit'
  # get 'books/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ブックモデルのルーティング
  # ブックコントローラ
  resources :books, only: [:edit, :create, :index, :show, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # # ホームのコントローラ
  root "homes#top"
  get "home/about" => "homes#index"


  # ユーザーモデルのルーティング
  # ユーザーコントローラ
  resources :users, only: [:show, :edit, :update, :index] do
    # フォローリスト
    get "followlist" => "relationships#followlist" 
    # フォロワーリスト
    get "followerlist" => "relationships#followerlist" 
  
  end


  # ログイン認証が成功した後、投稿画像の一覧画面が表示される
  # root 'books#index'

  # フォローのルーティング
  post 'create/:id' => 'relationships#create', as: 'create' # フォローする
  post 'destroy/:id' => 'relationships#destroy', as: 'destroy' # フォロー外す
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # ユーザーがファボしたかどうかを確認するメソッド
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { in: 1..200 }
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  # 1つツイートに1つのユーザーしかいいねができないよう制限
  validates :book_id, uniqueness: { scope: :user_id }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  
  # フォローする・フォロー外す・フォローしているか確認を行うメソッド
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
  
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


  # ログインしたあとに飛ぶページの設定
  def after_sign_in_path_for(resource)
    user_path(current_user.id) 
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @new = Book.new
    @book_comment = BookComment.new
    @book_comment_new = current_user.book_comments.new(book_comment_params)
    @book_comment_new.book_id = @book.id
    @user = current_user

   @book_comment_new.save

  end


  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    # redirect_to request.referrer
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
    redirect_to book_path(@book.id), notice: "You have creatad book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user.id != current_user.id
      redirect_to books_path
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_comment_new = BookComment.new
    @new = Book.new
    @user = current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
     render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: root_path)
    # redirect_to request.referrer
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)
    # redirect_to request.referrer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.all
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
      
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path, notice: "You have updated user successfully."
    else
     render :edit
    end

  end


  private
  def user_params
     params.require(:user).permit(:profile_image, :name, :introduction)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <div class="hana">
              <span>Bookers</span>
          </div>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to "Users", users_path, class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to "Books", books_path, class: "glyphicon glyphicon-book" %></li>
              <li><%= link_to "logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete %></li>
            <% else %>
              <li><%= link_to "Home", root_path, class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to "About", home_about_path, class: "glyphicon glyphicon-link" %></li>
              <li><%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %></li>
              <li><%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <!--条件分岐。ログインしてる時、してない時-->
    <div style="margin-top: 51px;">
      <%= yield %>
    </div>

    <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
         CopyRight Infratop.inc
        </div>
      </div>
    </div>
    </footer>
  </body>
</html>